name: Version update runner

on:
  pull_request:
    types: [closed]
    branches:
    - release
env:
  NAME_VERSION_FILE: version
  RELEASE_BRACH: release
  MINOR: minor
  PATCH: patch
  VERSION_UP: .github/workflows/version_up.py
  
jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse branch name
        id: parse-data
        uses: tj-actions/branch-names@v8

      - name: Print info about actions
        run: |
          echo "EVENT_NAME   ${{github.event_name}}"
          echo "ACTION       ${{github.event.action}}"
          echo "IS_PULL_REQUEST_MERGED   ${{github.pull_request.merged}}"
          echo "CURRENT_BRANCH     ${{steps.parse-data.outputs.current_branch}}"
          echo "REF          ${{github.ref}}"
          echo "REF_NAME     ${{github.ref_name}}"
          echo "DEFAULT_BRANCH  ${{steps.parse-data.outputs.default_branch}}"

  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch (feature/hotfix)
        id: validate_branch
        if: |
          contains(steps.parse-data.outputs.current_branch, 'feature') || 
          contains(steps.parse-data.outputs.current_branch, 'hotfix')
        run: echo "Valid branch"

      - name: Run minor version update script
        id: update-minor-version
        if: |
          contains(steps.parse-data.outputs.current_branch, 'feature')
        run: |
          python version_up.py minor

      - name: Run patch version update script
        id: update-patch-version
        if: |
          contains(steps.parse-data.outputs.current_branch, 'hotfix')
        run: |
          python version_up.py patch
  
